interface Env {
  VITE_LLM_PROVIDER: string;
  VITE_ANTHROPIC_API_KEY: string;
  VITE_ANTHROPIC_MODEL_NAME: string;
  VITE_OPENAI_API_KEY: string;
  VITE_OPENAI_MODEL_NAME: string;
  VITE_OPENAI_LIKE_BASE_URL: string;
  VITE_OPENAI_LIKE_API_KEY: string;
  VITE_OPENAI_LIKE_MODEL_NAME: string;
}
